allowBuilds:
  '@firebase/util': set this to true or false
  '@google/genai': set this to true or false
  '@openrouter/sdk': set this to true or false
  protobufjs: set this to true or false
  sharp: false
minimumReleaseAgeExclude:
  - '@openrouter/sdk@0.13.20'
  - '@ai-sdk/gateway@4.0.3'
  - '@ai-sdk/mcp@2.0.2'
  - '@ai-sdk/openai@4.0.1'
  - '@ai-sdk/react@4.0.4'
  - ai@7.0.3
  - cascadeflow-core-smr@1.1.1-smr.1 || 1.1.1-smr.2
  - cascadeflow-vercel-ai-smr@1.1.1-smr.1 || 1.1.1-smr.2
